# Generated by Django 4.2.25 on 2025-10-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=25)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('unidade_de_venda', models.CharField(max_length=8)),
                ('preco_unitario', models.DecimalField(decimal_places=3, max_digits=9)),
                ('quantidade_disponivel', models.DecimalField(decimal_places=3, max_digits=9)),
                ('data_ultima_atualizacao', models.TimeField()),
                ('data_validade', models.DateField(null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.TimeField(auto_now=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=3, default=0, max_digits=9, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.produto')),
            ],
        ),
    ]
